### ISSUE TITLE
Library did not sorted correctly when "alphabetically" is used.

### ISSUE THREAD

**Issue by MagnesG** [Jays2Kings/tachiyomi#11]
**App version:** v0.9.1

**Android version:** 9

**Issue/Request:** As the title stated with no filter used.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by Jays2Kings** [comment]
Can you give more detail about how it's sorted now?

**Comment by MagnesG** [comment]
I think it was sorted alphabetically for 2, 3 proper order then not, it was all over the place instead of (row,column) (1,1), (2,1) (3,1) (1,2) (2,2,) sequence .... For example of manga with an "A" in the front got sorted in the middle. 
Also I have all my manga from multiples sources, around 60 unique titles with 2 separated categories, both sorted out weirdly.
Sorry I wish I could provide screenshot or something but I have rom problems with my phone boot-looping, I can't access the app for now.

I think it's better for you to try the sorting option yourself, I did modified the library a couple of times before that and it still not sorting it "alphabetically" in the correct way.

**Comment by Jays2Kings** [comment]
It might be how I've made the alphabet sorting work. Words like "A", "An", and "The" aren't considered when sorting. If it's really bothering you I can add an option to sort without those words considered.

**Comment by MagnesG** [comment]
If it's possible, I will really appreciate it^^

It will become a hassle when there's close to hundred in my library.

**Comment by Jays2Kings** [comment]
As of 0.9.5, it's now sorting as it used to, with a setting to revert back how it was before 0.9.5
