### ISSUE TITLE
[Feature Request] Add search, sort and enable/disable toggle for Sources

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#12]
Currently, Sources page (in Catalogues) is a complete mess. I have several Multisource extensions and have over 80 sources and I only use like 10. ATM it's not very user friendly to enable a source as I have to scroll past dozens of them to find one.

I am requesting three features:

1. Search function for Source page similar to that for Extensions. 

2. Sorting, ie sources will grouped by enabled and disabled, with enabled sources on top. 

3. Toggle to enable/disable all sources. (If somebody uninstalls and reinstalled Tachi now, all sources are enabled by default and it's a huge pain to disable all of them manually, I had to disable over 70 sources one by one when I installed this fork)

Here's how it's for me now, please fix it :)

![screenshot_20191212-034022_tac](https://user-images.githubusercontent.com/34897862/70696377-9098f380-1c91-11ea-8af0-32499adaf6ac.jpg)

**Comment by Jays2Kings** [comment]
I've added all 3 features as part of 0.9.3
