### ISSUE TITLE
[Feature Requests] Pinch to Zoom Out

### ISSUE THREAD

**Issue by iAmPhilo** [Jays2Kings/tachiyomi#13]
App version: v0.9.1
Android version: Android 10

Hi, I was wondering if you could add pinch to zoom out feature, so you can see all the pages in the chapter and click to the right page straight away.

A good example is from MangaRock. Much appreciated. Fantastic fork, looking forward to the future of the app.

![Screenshot_20191214-101550](https://user-images.githubusercontent.com/58877905/70847280-b9b8b000-1e5a-11ea-9684-36638b3c56ba.png)

**Comment by Jays2Kings** [comment]
Thinking it over this for a while this would be incredibly complex to implement for functionally mirrored by the reader's seekbar. Pages are also downloaded about 2-3 at a time, so this would changing the download behavior.

It's a good feature, and it makes sense to add if there wasn't a seekbar (like how mangarock doesn't have), but sorry I can't justify trying to add this.
