### ISSUE TITLE
[Bug] Dark mode support for error message bar on the bottom

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#14]
Currently the bar on the bottom for the error messages (like http 401, No results found  etc) are white no matter white or dark mode. Please fix it.

![0-02-01-a3ff6f928368fcbaf22ca4024a10c17364c467670061d20489e9654a9d366d44_b447fdbc](https://user-images.githubusercontent.com/34897862/70859874-026a7a80-1ee8-11ea-8963-28b0bf28b22c.jpg)

Vanilla tachi darkens it properly.

**Comment by Jays2Kings** [comment]
On dark theme it is supposed to be white to stand out better as supported by material design comps.

"When a light surface is needed in a dark theme, light coloring can be used on select component surfaces to preserve hierarchy.

For example, a dark theme snackbar can display a light surface to help it stand out. To do so, it can apply the light theme’s Surface and On Surface colors."

![image](https://user-images.githubusercontent.com/8617760/70867663-aa099c00-1f2c-11ea-9663-73dda1d788dd.png)

On the light theme it will still be dark. You can see the same thing in other apps the support dark mode like gmail.

**Comment by joseph619** [comment]
Yeah but I use Amoled black, and the white on it looks really bad (excessive contrast). Material design doesn't use Amoled black, they use white on grey. I would appreciate if you keep white on grey but use grey for Amoled black, it looks really bad atm.

**Comment by jgasc12** [comment]
I get what you mean, alright I'll switch it back to grey for alomed

**Comment by joseph619** [comment]
Thanks bro, I will close this after next update.

**Comment by Jays2Kings** [comment]
Newest release has AMOLED using the dark snackbar again
