### ISSUE TITLE
[Feature Request] Bulk Source Migration

### ISSUE THREAD

**Issue by luiq54** [Jays2Kings/tachiyomi#16]
**App version: 0.9.3**

**Android version: 9**

**Issue/Request:**
In source migration menu, multiple titles with same source can be migrated to another one (if possible.)
If there's an error in migration, say certain title is not found in the latter source, show other possible sources to migrate for the particular title.

**Comment by joseph619** [comment]
If it helps, Nulldev's TachiyomiEh already has an Auto Migration feature, here's the commit for it

https://github.com/NerdNumber9/TachiyomiEH/commit/5b3e72db546ec66a2657d4db06cd504285ab494b

Here's his commit history, might help

https://github.com/NerdNumber9/TachiyomiEH/commits/master?after=c1c43bb6fbe9c967ebe474b9ec9f8f7d0c0c9ac9+34

**Comment by Jays2Kings** [comment]
Implemented as of 0.9.5
