### ISSUE TITLE
[Feature Request] Notification for extension update

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#17]
Requesting notification to inform user that an update for an installed extension is available. For example, when Mangabox is updated to 1.2.5 to 1.2.6, user will get a notification that an update for the extension is available (similar to how we get update for the app)

**Comment by Jays2Kings** [comment]
Added as of 0.9.4, in extensions -> overflow menu. Every day you'll get a notification similar to the gogole play store listing all the pending updates
