### ISSUE TITLE
[Feature Requests] Show a list of missing extensions when restoring backup 

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#2]
App version: 9.0.0

Android version: 9.0

Currently, when backups are restored without having all required extensions installed, it just shows that error occured, and users have to open the error log to see what manga failed to restore. This is very tedious and most phones do not have inbuilt log viewer.

It would be much easier if the app shows a message box with a list of missing extensions when backup is restored without all extensions.

For example:

> Restore took 00 min, 10 sec
> 17 errors found, please install the following extensions and restore again:
> Mangahere
> Mangasee
> Webtoons.com

**Comment by Jays2Kings** [comment]
Backups only have a long number for the source, not the source name, the number is meaningless unless you have the correct sources installed. Sadly there's no practical way to see the exact source that's missing. The newest update at least says that sources are missing and that you're not logged into a tracking site without needing to open the log
