### ISSUE TITLE
Library is taking forever to open. 

### ISSUE THREAD

**Issue by Saumyavilasroy** [Jays2Kings/tachiyomi#20]
App version:0.9.41

Android version: 8.0.0

Issue: I have about 250 titles in my library of Tachiyomi. And whenever I open the application or takes about 4-5 seconds to open it. 

Other details: I'm on a 3 gb ram phone with a octa core processor

**Comment by iAmPhilo** [comment]
Your storage is probably emmc, I have 350 mangas and no problem. I am using the Pixel 4 XL. What device are you using?

**Comment by Saumyavilasroy** [comment]
It was due to manga rock..
