### ISSUE TITLE
[Feature Request] Skip loading previous pages while using Seekbar

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#22]
### Why/User Benefit/User Problem

Currently if you decide to skip pages in the reader using seekbar (to find a particular scene for example), you have to wait for all the previous pages that were queued to finish loading.

### What/Requirements
Page loading should cancel for any pages that the user has skipped.

Example:

If I go to a previous chapter and scroll to near the beginning, the reader should not load all the pages I skipped in descending page number. It should, after scrolling has stopped (perhaps with a 1 or 2 second debounce), cancel any pending loads and immediately start loading from the page I ended up at.

Same applies If I were to skip forward in a chapter. 

This would improve seekbar scrolling and reduce loading time a lot. It could also potentially avoid temporary IP bans on certain sites. Perhaps an alternate solution to #13

**Comment by joseph619** [comment]
A PR has already been made for it (thanks to McAxiaz), maybe you can consider reviewing it

https://github.com/inorichi/tachiyomi/pull/2426#issuecomment-570894129

**Comment by Jays2Kings** [comment]
PR was merged into dev and is now in 0.9.55
