### ISSUE TITLE
[Feature Request] Move manga manually in My library 

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#23]
### Why/User Benefit/User Problem
User can move around favorites in My library in randomly by long pressing and dragging it, if they do not want the library to be organized just by current parameters (like Last updated, Last read etc). It would be better if the moving worked alongside the parameters (like I want favorites be in order of Last updated, but still want a certain manga first on the list).

### What/Requirements
A toggle in the sidebar of My Library (under Sort, maybe) to enable dragging where users can move around their favorite manga randomly. Disabling would lock it again, and changing the parameter (ie. from Last updated to Last read) would reset the order.

It's up to you to decide whether the order is still intact in backups (if possible). I don't mind either way, it's originally requested here (https://github.com/inorichi/tachiyomi/issues/2374)

**Comment by Jays2Kings** [comment]
A shuffle option in the sort sidebar can be possible (saving it in backups not so much), however in your opinion would you think a "pick a random manga/i'm feeling lucky" button would be better?

I'm also not sure how one would mix one sorting method with a shuffle

**Comment by joseph619** [comment]
Well you can add that too if you want, although I am not sure if users would need a random manga from Library, since they're most likely familiar with all the favorites.

Shuffle wouldn't disable the sorting method right? So shouldn't it work on top of them?

**Comment by joseph619** [comment]
I have edited the request, changed shuffle to manually move manga in library (by long pressing it and moving the thumbnail around). Would that be possible?

**Comment by Jays2Kings** [comment]
I can't tell you off the top of my head if it is, since the long press is currently dedicated to selecting multiple manga, idk if android has a solution built in for long press vs long press and drag, but I'll get back to you on it

**Comment by Jays2Kings** [comment]
This somehow squeezed its way into 0.9.55 but it's been mostly tested and works. Long pressing can be used to move manga around, and there's a new option in the 3 dots to reorder the manga in a category
