### ISSUE TITLE
[Feature Request] Tag searching and multiple tag searching in library is broken

### ISSUE THREAD

**Issue by namelesstcym** [Jays2Kings/tachiyomi#24]
**App version:** 
0.9.41

**Android version:**
Android 9

**Issue/Request:**
Tag searching and multiple tag searching in library is broken. Only a few manga shows up when I search a tag. For example; I have 20 romance & comedy manga, when I try to search for "Romance" or "Comedy", only 6 of  them shows up. When I search using 2 tags, no manga shows up. I tried using "," "&", "$" and ";" to separate the tags and it doesn't work.

**Steps to reproduce (if applicable)**
 1. Search a tag in the library, single or multiple tags

**Other details:**
I see that some manga doesn't show their sources.

![Screenshot_2019-12-27-17-46-38-250_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/59281533/71514076-f93cbe80-2894-11ea-9fd4-1429c11a6b67.jpg)
![Screenshot_2019-12-27-18-33-27-731_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/59281533/71514077-f93cbe80-2894-11ea-939b-1206c31d44d0.jpg)
![Screenshot_2019-12-27-18-33-36-984_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/59281533/71514078-f93cbe80-2894-11ea-9a25-c7e7902c0851.jpg)
![Screenshot_2019-12-27-18-33-42-546_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/59281533/71514079-f9d55500-2894-11ea-8154-a4f672873ecd.jpg)
![Screenshot_2019-12-27-18-33-48-908_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/59281533/71514080-f9d55500-2894-11ea-9dea-278429dd0f29.jpg)

**Comment by Jays2Kings** [comment]
Multiple tags currently isn't supported. Some of the tags searching isn't working because I can see the tag for that manga says "Romance " not "Romance" (notice the space). 

I'll try to see if I can cut out the space in the tags for searching, but multiple tags will take a while

**Comment by Jays2Kings** [comment]
Both this bug and multi tag searching is in as of 0.9.5
