### ISSUE TITLE
[Feature Request] Hide already-added items in catalog

### ISSUE THREAD

**Issue by MxFlix** [Jays2Kings/tachiyomi#25]
Currently, when browsing a catalog, titles that are already in the user's library are faded out. It would be convenient for quick browsing to instead have the option to completely hide those items instead. 
I guess an additional option would be needed concerning whether newly-added items should be immediately hidden, or stay visible until the list is loaded again.
And it would probably have to come with a warning that it would lead to a lot more requests to the server to fill a single page.

**Comment by joseph619** [comment]
What is the benefit of this though? It might seem like those favorites don't actually exist in the source if they're hidden.

**Comment by Jays2Kings** [comment]
The implementation of this is would be a lot of effort for all the use cases you mentioned plus more for a minor feature. Sorry but I don't think I'll be the one to implement this.
