### ISSUE TITLE
Chapter list opens in the middle

### ISSUE THREAD

**Issue by m-vlad** [Jays2Kings/tachiyomi#27]
**App version:** 0.9.4.1

**Android version:** 10

**Issue/Request:** chapter lists opens in the middle of the list when chapter list order is reversed.

**Steps to reproduce (if applicable)**

 1. Bookmark a manga that has more chapters than the viewfinder
 2. Reverse chapter order list
 3. Exit manga and re-enter it

**Other details:**

**Comment by Jays2Kings** [comment]
It's another case of "it's not a bug it's a feature". Chapters screen try to put the latest unread chapter in the middle of the screen if possible, if it can't it just goes to the top or bottom of the screen. 

For example if you are Midway in manga and open it, you'll see the next unread chapter right under your finger

**Comment by m-vlad** [comment]
But that's the thing, I'm nowhere near that place, i usually filter it to Unread only and it keeps going down to the middle of the chapter list.

**Comment by Jays2Kings** [comment]
Do you mind providing a screenshot of where it lands, what manga, and a rough idea what's read or unread of it? I can see it not going to the right place with the unread filter and read chapters all over the place.

**Comment by m-vlad** [comment]
Huh, weird, I'm trying to replicate the situation (It was volcanic age and I was at about chapter 60 but now it's working properly, even with no filters set up. Guess we'll never find out.
