### ISSUE TITLE
Chapters not always deleting

### ISSUE THREAD

**Issue by m-vlad** [Jays2Kings/tachiyomi#28]
**App version:** 0.9.41

**Android version:** 10

**Issue/Request:** manga chapters don't delete even though the setting is enabled

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by Jays2Kings** [comment]
Can you explain more, what setting(s)? What did you do notice this?

**Comment by m-vlad** [comment]
I've got "Remove when marked as read" enabled and it's ste to remove the last read chapter. I just read the mangas and then they still show up as Downloaded after that. Even when marked as read manually (whereas in the og tachiyomi it'd delete the chapter)

**Comment by joseph619** [comment]
I have the same issue as well, Auto delete chapters has not worked for me for months.

**Comment by Jays2Kings** [comment]
I just checked dev tachi and marking something as read doesn't delete a chapter either. I'll try to make a fix for it as it was probably just missed.

**Comment by CarlosEsco** [comment]
Do you guys have the mark as read delete enabled in options?

**Comment by m-vlad** [comment]
> I've got "Remove when marked as read" enabled and it's ste to remove the last read chapter. I just read the mangas and then they still show up as Downloaded after that. Even when marked as read manually (whereas in the og tachiyomi it'd delete the chapter).

**Comment by CarlosEsco** [comment]
So it worked when you long press and then 3 dot at top mark as read.  But not when you 3 dot directly on the chapter

**Comment by m-vlad** [comment]
No, it doesn't work at all. But for some reason some chapters get deleted and some don't. Mostly don't, which makes me think i've been deleting the rest and forgot I did so.

**Comment by CarlosEsco** [comment]
Are you sure it's not just ui issue?  It shows downloaded after I click mark as read. But then when I mark as unread the chapter doesn't show downloaded

**Comment by joseph619** [comment]
Nah, not UI issue. I checked the downloads folder and the chapters are still there. It broken all right.

**Comment by Jays2Kings** [comment]
Fixed as of 0.9.5 (or 0.9.55 I'm very tired)
