### ISSUE TITLE
[Feature request] Global Search only on selected sources

### ISSUE THREAD

**Issue by pervertkirito** [Jays2Kings/tachiyomi#29]
**Request:** add option to pick only selected source to be included on global search

**Other details:** I would like to search only on aggregator source.
At least can disable which source have slow connection, so global Search not so slow

**Comment by Jays2Kings** [comment]
You can disable sources by tapping the gear icon in catalogues, and that is directly tied to global search. Adding a secondary setting for this would needlessly complicate things.
