### ISSUE TITLE
[Feature Request] Add custom genre tag filtering in Categories

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#6]
This feature would allow people to assign custom genre tags for their favourites in Categories and filter them. It would be nice to add an option for the tags to either work across all Categories sections or just individual categories.

**Comment by Jays2Kings** [comment]
I mean to ask about this a while ago, but could you explain a bit more what you're asking for. Currently this fork lets you search through tags in the library, and if you click on a tag in the manga page, it'll search your library for manga that matches the tag

**Comment by joseph619** [comment]
Actually this is an old feature request, I am happy with the current tag system as it is.
