### ISSUE TITLE
[Feature Request] Enable search for source within Multi-source extension

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#7]
For example, under extensions menu if I look up Manhwa Club, it would return Madara (as Manhwa Club is part of Madara multisource extension).

**Comment by Jays2Kings** [comment]
Can't say this one will be possible, since it's not known what extension has what until its installed

**Comment by joseph619** [comment]
All right, this was is a bit too much to ask for now perhaps. I will close this then, please look into the other requests :)

**Comment by ardittristan** [comment]
I don't know how feasable this would be in an app, but what i did for my automated text script on pc was scan the github factory files with regex to find sources
