### ISSUE TITLE
[Feature Reqest] Allow back button to navigate to previous URL in WebView

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#8]
Adds Forward, Refresh, and Close actions to webview controller menu

A PR has already been made, you can use that your make your own PR if you want

https://github.com/inorichi/tachiyomi/pull/2176

**Comment by Jays2Kings** [comment]
v9 already supports going back and forward, as well as an X (Close button) to leave the webview

**Comment by joseph619** [comment]
Thanks, I will close this then.
